_assignments/README.md
=> add rubric documentation

_assignments/important_notes.md, _config.yml
To stress it more on the site itself.
=> Updated with Unity version info

_assignments/README.md, _assignments/mp3.md, _layouts/assignment.html
Addresses #25. Due date is tentative, based off the calendar in planning doc
=> MP3 converted

_assignments/project.md
Based off of last-minute changes
=> Updating grading weights

_assignments/mp4.md
=> Updated MP4 due date

_assignments/README.md, _assignments/grad_assignment.md, _assignments/mp1.md, _assignments/mp2.md, _assignments/mp3.md, _assignments/mp4.md, _assignments/project.md, _layouts/assignments.html
You can now order assignments by the new `assignment` property in the assignment frontmatter. This allows us to sort things arbitrarily. Addresses #96.
=> Sortable assignments

extra-material.md
Feel free to add more resources!
=> Added some additional resources for best practices in VR

_sass/vrsite/project.scss
| before | after |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/6186771/54416692-1f122180-46ce-11e9-8571-e784c0ad1e03.png) | ![image](https://user-images.githubusercontent.com/6186771/54416732-381ad280-46ce-11e9-9888-6ff490571470.png) |
I was bored ok...
=> Fixed padding on mobile

_layouts/default.html, _sass/vrsite/fool.scss, assets/main.scss, assets/szn.js
=> this is entirely a waste of time

_sass/vrsite/fool.scss, assets/szn.js
=> Fixed close forever

README.md, _layouts/assignment.html, _sass/vrsite/assignment.scss, _sass/vrsite/sections.scss, assets/collapse-sections.js, assets/szn.js
- Made April Fool's modal less annoying in development
- changed Mathjax script to `defer` so it doesn't block DOM rendering
Addresses #88
=> Modularized collapsible sections, and a couple other changes

_projects/SP19-EventHorizon.md
Team 12: yxzhang2, painap2, sujalfs2, blyu3, weihang2
=> Request: Team 12 - Event Horizon

_projects/SP19-SavannahPlaneVR.md
=> Team 6 submission, cleaned up

_assignments/README.md, _assignments/important_notes.md, _layouts/assignment.html, _layouts/assignments.html, assignments.md
Sort by "index" key, not "assignment"  (ambiguous)
Typo and HTML cleanup
=> Improve assignments pages

_assignments/mp1.md
Condensed version of the old MP1, this time with only one part. It's still due in two weeks (from this Wednesday).
The majority of the work is the same, just only in one room this time.
Prose content is mostly the same but has been drastically reordered.
=> Add new MP1 for FA19

_assignments/vr-critic.md
This combines the MP1 review experience into what was formerly "MP3", and is otherwise identical to MP3.
Due date fixed to two weeks from Wednesday.
=> Add VR critic assignment for FA19

_assignments/mp4.md
I pull this MP4 from the latest commit before Eric remove it.
Time limit is 2 weeks rather than 4 weeks.
I want to emphasize in the docs that no extension will be granted even there is a technical issue on the lab machines. Two weeks is the hard deadline. If we plan to have extension near the deadline, we are just delaying progress on student project. I want to encourage student to start earlier while we reduced some workload for the assignment.
=> MP4 release

_assignments/mp3.md
Make sure to add the mp3 package to the mps folder and change the name to mp3.unitypackage
=> added mp3 instructions

_assignments/mp1.md
Prevent Piazza 66 from happening again.
Note that this will gradually need to be updated as the lab changes Unity versions.
=> Update MP1 modeling tools

_assignments/mp4_nolab.md
DONT MERGE UNTIL PACKAGES FIXED
=> Add MP4 no lab spec
